---
AWSTemplateFormatVersion: 2010-09-09

Description: Create a trail.

Resources:
  #-----------------------------------------------------------------------------
  # Trail
  #-----------------------------------------------------------------------------
  SentinelTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: sentinel-trail
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      S3BucketName: !ImportValue CloudtrailBucket
      KMSKeyId: !ImportValue SentinelKeyAlias
      EventSelectors:
        - IncludeManagementEvents: true
          DataResources:
            - Type: AWS::S3::Object
          ReadWriteType: All
      IsLogging: true
