AWSTemplateFormatVersion: 2010-09-09

Description: Create buckets, bucket policies.
Resources:
  #-----------------------------------------------------------------------------
  # Buckets
  #-----------------------------------------------------------------------------
  AnsiblePlaybooksBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ansible-playbooks-${AWS::AccountId}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: Pending
          - id: W41
            reason: Pending
          - id: W51
            reason: Pending

  #-----------------------------------------------------------------------------
  # Bucket policies
  #-----------------------------------------------------------------------------

Outputs:
  AnsiblePlaybooksBucket:
    Value: !Ref AnsiblePlaybooksBucket
    Export:
      Name: AnsiblePlaybooksBucket

  # CloudtrailBucketArn:
  #   Value: !GetAtt CloudtrailBucket.Arn
  #   Export:
  #     Name: CloudtrailBucketArn

  # GuarddutyBucketArn:
  #   Value: !GetAtt GuarddutyBucket.Arn
  #   Export:
  #     Name: GuarddutyBucketArn
