name: Run cfn-nag

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: ./cfn/templates
          extra_args: --fail-on-warnings
