name: Run cfn-lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      # Add a matcher file to parse cfn-lint warnings.
      - name: Add problem matcher
        run: echo "::add-matcher::.github/cfn-lint.json"

      # With '-f parseable', each warnings are printed out on a sinble line.
      - name: Run cfn-lint
        run: cfn-lint ./cfn/templates/*.yml -f parseable
